# Change these first
# lunar-d/WebStats/
owner: lunar-d # Your GitHub username
repo: WebStats # Your GitHub repository name

# Add your sites here
sites:
  - name: LunarDreams (Principale)
    url: https://lunardreams.fr
  - name: LunarDreams (Domaine de repli)
    url: https://lunard.ynh.fr/yunohost/
  - name: Routeur
    url: $IPBOX

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: stats.lunardreams.fr
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  
  # Etat des services disponibles sur lunardreams.fr alimenté par Upptime.
  # Si l'un des services ne réponds pas merci de me contacter sur GitHub ou par mail.
  introTitle: "Etats des services disponibles sur [**lunardreams.fr**](https://lunardreams.fr) alimenté par [Upptime](https://github.com/upptime/upptime)."
  introMessage: "Si l'un des services ne réponds pas merci de me contacter sur Discord ou par mail."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: LunarDreams
      href: https://lunardreams.fr

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
